### ISSUE TITLE
提交两个小bug

### ISSUE THREAD

**Issue by tanlentboy** [JeremywangCN/coin-cryptocurrency-exchange#5]
感谢作者分享此源码供学习交流。

安装使用中遇到两个问题：
1.  service\keystorebch.js 中  BCHConfig 这里模块插入错误了，  分了下大小写   ./../config/bchconfig
 var BCHConfig = require('./../config/BCHConfig')//Bitcoin Cash Configurations  

2.scripts/create_database.js  创建数据库的时候老是执行错误，不是数据库的数据库和语法的问题，我的环境始终无法执行多行 数据语句，建议用 mysql.sql 导入。

**Comment by cryptocurpays** [comment]
Fixed the first issue. Thanks
